# Generated by Django 3.2.14 on 2022-07-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='options',
            field=models.ManyToManyField(related_name='options', to='Quiz.Option'),
        ),
    ]
