# Generated by Django 3.2.14 on 2022-07-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_question_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='option',
            name='is_answer',
            field=models.BooleanField(default=False),
        ),
    ]
